#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCoCard.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbWebForm")]
	public partial class CoCardDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMAS_FORM_CO_CARD_CHOICE(MAS_FORM_CO_CARD_CHOICE instance);
    partial void UpdateMAS_FORM_CO_CARD_CHOICE(MAS_FORM_CO_CARD_CHOICE instance);
    partial void DeleteMAS_FORM_CO_CARD_CHOICE(MAS_FORM_CO_CARD_CHOICE instance);
    partial void InsertMAS_FORM_CO_CARD_SETTING(MAS_FORM_CO_CARD_SETTING instance);
    partial void UpdateMAS_FORM_CO_CARD_SETTING(MAS_FORM_CO_CARD_SETTING instance);
    partial void DeleteMAS_FORM_CO_CARD_SETTING(MAS_FORM_CO_CARD_SETTING instance);
    partial void InsertTRN_FORM_CO_CARD(TRN_FORM_CO_CARD instance);
    partial void UpdateTRN_FORM_CO_CARD(TRN_FORM_CO_CARD instance);
    partial void DeleteTRN_FORM_CO_CARD(TRN_FORM_CO_CARD instance);
    #endregion
		
		public CoCardDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbWebFormConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CoCardDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoCardDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoCardDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CoCardDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MAS_FORM_CO_CARD_CHOICE> MAS_FORM_CO_CARD_CHOICEs
		{
			get
			{
				return this.GetTable<MAS_FORM_CO_CARD_CHOICE>();
			}
		}
		
		public System.Data.Linq.Table<MAS_FORM_CO_CARD_SETTING> MAS_FORM_CO_CARD_SETTINGs
		{
			get
			{
				return this.GetTable<MAS_FORM_CO_CARD_SETTING>();
			}
		}
		
		public System.Data.Linq.Table<TRN_FORM_CO_CARD> TRN_FORM_CO_CARDs
		{
			get
			{
				return this.GetTable<TRN_FORM_CO_CARD>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_FORM_CO_CARD_CHOICE")]
	public partial class MAS_FORM_CO_CARD_CHOICE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CHOICE_ID;
		
		private int _CAMPAIGN__ID;
		
		private byte _CHOICE_NO;
		
		private string _CHOICE_CAPTION;
		
		private int _CFLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCHOICE_IDChanging(long value);
    partial void OnCHOICE_IDChanged();
    partial void OnCAMPAIGN__IDChanging(int value);
    partial void OnCAMPAIGN__IDChanged();
    partial void OnCHOICE_NOChanging(byte value);
    partial void OnCHOICE_NOChanged();
    partial void OnCHOICE_CAPTIONChanging(string value);
    partial void OnCHOICE_CAPTIONChanged();
    partial void OnCFLAGChanging(int value);
    partial void OnCFLAGChanged();
    #endregion
		
		public MAS_FORM_CO_CARD_CHOICE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHOICE_ID", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long CHOICE_ID
		{
			get
			{
				return this._CHOICE_ID;
			}
			set
			{
				if ((this._CHOICE_ID != value))
				{
					this.OnCHOICE_IDChanging(value);
					this.SendPropertyChanging();
					this._CHOICE_ID = value;
					this.SendPropertyChanged("CHOICE_ID");
					this.OnCHOICE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAMPAIGN__ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CAMPAIGN__ID
		{
			get
			{
				return this._CAMPAIGN__ID;
			}
			set
			{
				if ((this._CAMPAIGN__ID != value))
				{
					this.OnCAMPAIGN__IDChanging(value);
					this.SendPropertyChanging();
					this._CAMPAIGN__ID = value;
					this.SendPropertyChanged("CAMPAIGN__ID");
					this.OnCAMPAIGN__IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHOICE_NO", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte CHOICE_NO
		{
			get
			{
				return this._CHOICE_NO;
			}
			set
			{
				if ((this._CHOICE_NO != value))
				{
					this.OnCHOICE_NOChanging(value);
					this.SendPropertyChanging();
					this._CHOICE_NO = value;
					this.SendPropertyChanged("CHOICE_NO");
					this.OnCHOICE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHOICE_CAPTION", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CHOICE_CAPTION
		{
			get
			{
				return this._CHOICE_CAPTION;
			}
			set
			{
				if ((this._CHOICE_CAPTION != value))
				{
					this.OnCHOICE_CAPTIONChanging(value);
					this.SendPropertyChanging();
					this._CHOICE_CAPTION = value;
					this.SendPropertyChanged("CHOICE_CAPTION");
					this.OnCHOICE_CAPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFLAG", DbType="Int NOT NULL")]
		public int CFLAG
		{
			get
			{
				return this._CFLAG;
			}
			set
			{
				if ((this._CFLAG != value))
				{
					this.OnCFLAGChanging(value);
					this.SendPropertyChanging();
					this._CFLAG = value;
					this.SendPropertyChanged("CFLAG");
					this.OnCFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_FORM_CO_CARD_SETTING")]
	public partial class MAS_FORM_CO_CARD_SETTING : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CAMPAIGN_ID;
		
		private string _BRAND_NAME;
		
		private string _CAMPAIGN_NAME;
		
		private string _FORM_CAPTION;
		
		private System.Nullable<System.DateTime> _START_DATE;
		
		private System.Nullable<System.DateTime> _END_DATE;
		
		private int _CFLAG;
		
		private int _GRPDETAIL;
		
		private int _GRPFGF;
		
		private int _GRPDISCOUNT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCAMPAIGN_IDChanging(int value);
    partial void OnCAMPAIGN_IDChanged();
    partial void OnBRAND_NAMEChanging(string value);
    partial void OnBRAND_NAMEChanged();
    partial void OnCAMPAIGN_NAMEChanging(string value);
    partial void OnCAMPAIGN_NAMEChanged();
    partial void OnFORM_CAPTIONChanging(string value);
    partial void OnFORM_CAPTIONChanged();
    partial void OnSTART_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTART_DATEChanged();
    partial void OnEND_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEND_DATEChanged();
    partial void OnCFLAGChanging(int value);
    partial void OnCFLAGChanged();
    partial void OnGRPDETAILChanging(int value);
    partial void OnGRPDETAILChanged();
    partial void OnGRPFGFChanging(int value);
    partial void OnGRPFGFChanged();
    partial void OnGRPDISCOUNTChanging(int value);
    partial void OnGRPDISCOUNTChanged();
    #endregion
		
		public MAS_FORM_CO_CARD_SETTING()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAMPAIGN_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CAMPAIGN_ID
		{
			get
			{
				return this._CAMPAIGN_ID;
			}
			set
			{
				if ((this._CAMPAIGN_ID != value))
				{
					this.OnCAMPAIGN_IDChanging(value);
					this.SendPropertyChanging();
					this._CAMPAIGN_ID = value;
					this.SendPropertyChanged("CAMPAIGN_ID");
					this.OnCAMPAIGN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND_NAME", DbType="NVarChar(50)")]
		public string BRAND_NAME
		{
			get
			{
				return this._BRAND_NAME;
			}
			set
			{
				if ((this._BRAND_NAME != value))
				{
					this.OnBRAND_NAMEChanging(value);
					this.SendPropertyChanging();
					this._BRAND_NAME = value;
					this.SendPropertyChanged("BRAND_NAME");
					this.OnBRAND_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAMPAIGN_NAME", DbType="NVarChar(255)")]
		public string CAMPAIGN_NAME
		{
			get
			{
				return this._CAMPAIGN_NAME;
			}
			set
			{
				if ((this._CAMPAIGN_NAME != value))
				{
					this.OnCAMPAIGN_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CAMPAIGN_NAME = value;
					this.SendPropertyChanged("CAMPAIGN_NAME");
					this.OnCAMPAIGN_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORM_CAPTION", DbType="NVarChar(MAX)")]
		public string FORM_CAPTION
		{
			get
			{
				return this._FORM_CAPTION;
			}
			set
			{
				if ((this._FORM_CAPTION != value))
				{
					this.OnFORM_CAPTIONChanging(value);
					this.SendPropertyChanging();
					this._FORM_CAPTION = value;
					this.SendPropertyChanged("FORM_CAPTION");
					this.OnFORM_CAPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> START_DATE
		{
			get
			{
				return this._START_DATE;
			}
			set
			{
				if ((this._START_DATE != value))
				{
					this.OnSTART_DATEChanging(value);
					this.SendPropertyChanging();
					this._START_DATE = value;
					this.SendPropertyChanged("START_DATE");
					this.OnSTART_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> END_DATE
		{
			get
			{
				return this._END_DATE;
			}
			set
			{
				if ((this._END_DATE != value))
				{
					this.OnEND_DATEChanging(value);
					this.SendPropertyChanging();
					this._END_DATE = value;
					this.SendPropertyChanged("END_DATE");
					this.OnEND_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFLAG", DbType="Int NOT NULL")]
		public int CFLAG
		{
			get
			{
				return this._CFLAG;
			}
			set
			{
				if ((this._CFLAG != value))
				{
					this.OnCFLAGChanging(value);
					this.SendPropertyChanging();
					this._CFLAG = value;
					this.SendPropertyChanged("CFLAG");
					this.OnCFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRPDETAIL", DbType="Int NOT NULL")]
		public int GRPDETAIL
		{
			get
			{
				return this._GRPDETAIL;
			}
			set
			{
				if ((this._GRPDETAIL != value))
				{
					this.OnGRPDETAILChanging(value);
					this.SendPropertyChanging();
					this._GRPDETAIL = value;
					this.SendPropertyChanged("GRPDETAIL");
					this.OnGRPDETAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRPFGF", DbType="Int NOT NULL")]
		public int GRPFGF
		{
			get
			{
				return this._GRPFGF;
			}
			set
			{
				if ((this._GRPFGF != value))
				{
					this.OnGRPFGFChanging(value);
					this.SendPropertyChanging();
					this._GRPFGF = value;
					this.SendPropertyChanged("GRPFGF");
					this.OnGRPFGFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRPDISCOUNT", DbType="Int NOT NULL")]
		public int GRPDISCOUNT
		{
			get
			{
				return this._GRPDISCOUNT;
			}
			set
			{
				if ((this._GRPDISCOUNT != value))
				{
					this.OnGRPDISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._GRPDISCOUNT = value;
					this.SendPropertyChanged("GRPDISCOUNT");
					this.OnGRPDISCOUNTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRN_FORM_CO_CARD")]
	public partial class TRN_FORM_CO_CARD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ROWNO;
		
		private int _CAMPAIGN_ID;
		
		private System.DateTime _WORKDATE;
		
		private string _ABBNO;
		
		private string _ADDR_FULLNAME;
		
		private string _ADDR_MOBILE;
		
		private string _WHCODE;
		
		private string _WHNAME;
		
		private string _STCODE;
		
		private string _STNAME;
		
		private int _FLAG;
		
		private string _DISCOUNT;
		
		private System.Nullable<System.DateTime> _SYSCRATE;
		
		private bool _FGF;
		
		private string _FGF_CARDID;
		
		private string _FGF_ABBNO;
		
		private System.Nullable<System.DateTime> _FGF_SALEDATE;
		
		private string _FGF_CARDID_FRIEND;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnROWNOChanging(long value);
    partial void OnROWNOChanged();
    partial void OnCAMPAIGN_IDChanging(int value);
    partial void OnCAMPAIGN_IDChanged();
    partial void OnWORKDATEChanging(System.DateTime value);
    partial void OnWORKDATEChanged();
    partial void OnABBNOChanging(string value);
    partial void OnABBNOChanged();
    partial void OnADDR_FULLNAMEChanging(string value);
    partial void OnADDR_FULLNAMEChanged();
    partial void OnADDR_MOBILEChanging(string value);
    partial void OnADDR_MOBILEChanged();
    partial void OnWHCODEChanging(string value);
    partial void OnWHCODEChanged();
    partial void OnWHNAMEChanging(string value);
    partial void OnWHNAMEChanged();
    partial void OnSTCODEChanging(string value);
    partial void OnSTCODEChanged();
    partial void OnSTNAMEChanging(string value);
    partial void OnSTNAMEChanged();
    partial void OnFLAGChanging(int value);
    partial void OnFLAGChanged();
    partial void OnDISCOUNTChanging(string value);
    partial void OnDISCOUNTChanged();
    partial void OnSYSCRATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSYSCRATEChanged();
    partial void OnFGFChanging(bool value);
    partial void OnFGFChanged();
    partial void OnFGF_CARDIDChanging(string value);
    partial void OnFGF_CARDIDChanged();
    partial void OnFGF_ABBNOChanging(string value);
    partial void OnFGF_ABBNOChanged();
    partial void OnFGF_SALEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnFGF_SALEDATEChanged();
    partial void OnFGF_CARDID_FRIENDChanging(string value);
    partial void OnFGF_CARDID_FRIENDChanged();
    #endregion
		
		public TRN_FORM_CO_CARD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWNO", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ROWNO
		{
			get
			{
				return this._ROWNO;
			}
			set
			{
				if ((this._ROWNO != value))
				{
					this.OnROWNOChanging(value);
					this.SendPropertyChanging();
					this._ROWNO = value;
					this.SendPropertyChanged("ROWNO");
					this.OnROWNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAMPAIGN_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CAMPAIGN_ID
		{
			get
			{
				return this._CAMPAIGN_ID;
			}
			set
			{
				if ((this._CAMPAIGN_ID != value))
				{
					this.OnCAMPAIGN_IDChanging(value);
					this.SendPropertyChanging();
					this._CAMPAIGN_ID = value;
					this.SendPropertyChanged("CAMPAIGN_ID");
					this.OnCAMPAIGN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this.OnWORKDATEChanging(value);
					this.SendPropertyChanging();
					this._WORKDATE = value;
					this.SendPropertyChanged("WORKDATE");
					this.OnWORKDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNO", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ABBNO
		{
			get
			{
				return this._ABBNO;
			}
			set
			{
				if ((this._ABBNO != value))
				{
					this.OnABBNOChanging(value);
					this.SendPropertyChanging();
					this._ABBNO = value;
					this.SendPropertyChanged("ABBNO");
					this.OnABBNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR_FULLNAME", DbType="VarChar(100)")]
		public string ADDR_FULLNAME
		{
			get
			{
				return this._ADDR_FULLNAME;
			}
			set
			{
				if ((this._ADDR_FULLNAME != value))
				{
					this.OnADDR_FULLNAMEChanging(value);
					this.SendPropertyChanging();
					this._ADDR_FULLNAME = value;
					this.SendPropertyChanged("ADDR_FULLNAME");
					this.OnADDR_FULLNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR_MOBILE", DbType="VarChar(50)")]
		public string ADDR_MOBILE
		{
			get
			{
				return this._ADDR_MOBILE;
			}
			set
			{
				if ((this._ADDR_MOBILE != value))
				{
					this.OnADDR_MOBILEChanging(value);
					this.SendPropertyChanging();
					this._ADDR_MOBILE = value;
					this.SendPropertyChanged("ADDR_MOBILE");
					this.OnADDR_MOBILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WHCODE", DbType="VarChar(50)")]
		public string WHCODE
		{
			get
			{
				return this._WHCODE;
			}
			set
			{
				if ((this._WHCODE != value))
				{
					this.OnWHCODEChanging(value);
					this.SendPropertyChanging();
					this._WHCODE = value;
					this.SendPropertyChanged("WHCODE");
					this.OnWHCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WHNAME", DbType="VarChar(50)")]
		public string WHNAME
		{
			get
			{
				return this._WHNAME;
			}
			set
			{
				if ((this._WHNAME != value))
				{
					this.OnWHNAMEChanging(value);
					this.SendPropertyChanging();
					this._WHNAME = value;
					this.SendPropertyChanged("WHNAME");
					this.OnWHNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(50)")]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this.OnSTCODEChanging(value);
					this.SendPropertyChanging();
					this._STCODE = value;
					this.SendPropertyChanged("STCODE");
					this.OnSTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STNAME", DbType="VarChar(100)")]
		public string STNAME
		{
			get
			{
				return this._STNAME;
			}
			set
			{
				if ((this._STNAME != value))
				{
					this.OnSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._STNAME = value;
					this.SendPropertyChanged("STNAME");
					this.OnSTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int NOT NULL")]
		public int FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DISCOUNT
		{
			get
			{
				return this._DISCOUNT;
			}
			set
			{
				if ((this._DISCOUNT != value))
				{
					this.OnDISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._DISCOUNT = value;
					this.SendPropertyChanged("DISCOUNT");
					this.OnDISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSCRATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SYSCRATE
		{
			get
			{
				return this._SYSCRATE;
			}
			set
			{
				if ((this._SYSCRATE != value))
				{
					this.OnSYSCRATEChanging(value);
					this.SendPropertyChanging();
					this._SYSCRATE = value;
					this.SendPropertyChanged("SYSCRATE");
					this.OnSYSCRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FGF", DbType="Bit NOT NULL")]
		public bool FGF
		{
			get
			{
				return this._FGF;
			}
			set
			{
				if ((this._FGF != value))
				{
					this.OnFGFChanging(value);
					this.SendPropertyChanging();
					this._FGF = value;
					this.SendPropertyChanged("FGF");
					this.OnFGFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FGF_CARDID", DbType="VarChar(50)")]
		public string FGF_CARDID
		{
			get
			{
				return this._FGF_CARDID;
			}
			set
			{
				if ((this._FGF_CARDID != value))
				{
					this.OnFGF_CARDIDChanging(value);
					this.SendPropertyChanging();
					this._FGF_CARDID = value;
					this.SendPropertyChanged("FGF_CARDID");
					this.OnFGF_CARDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FGF_ABBNO", DbType="VarChar(50)")]
		public string FGF_ABBNO
		{
			get
			{
				return this._FGF_ABBNO;
			}
			set
			{
				if ((this._FGF_ABBNO != value))
				{
					this.OnFGF_ABBNOChanging(value);
					this.SendPropertyChanging();
					this._FGF_ABBNO = value;
					this.SendPropertyChanged("FGF_ABBNO");
					this.OnFGF_ABBNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FGF_SALEDATE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FGF_SALEDATE
		{
			get
			{
				return this._FGF_SALEDATE;
			}
			set
			{
				if ((this._FGF_SALEDATE != value))
				{
					this.OnFGF_SALEDATEChanging(value);
					this.SendPropertyChanging();
					this._FGF_SALEDATE = value;
					this.SendPropertyChanged("FGF_SALEDATE");
					this.OnFGF_SALEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FGF_CARDID_FRIEND", DbType="VarChar(50)")]
		public string FGF_CARDID_FRIEND
		{
			get
			{
				return this._FGF_CARDID_FRIEND;
			}
			set
			{
				if ((this._FGF_CARDID_FRIEND != value))
				{
					this.OnFGF_CARDID_FRIENDChanging(value);
					this.SendPropertyChanging();
					this._FGF_CARDID_FRIEND = value;
					this.SendPropertyChanged("FGF_CARDID_FRIEND");
					this.OnFGF_CARDID_FRIENDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
